name: GitHub Metrics

on:
  # Permite execução manual do workflow
  workflow_dispatch:

  # Executa automaticamente todo dia às 6h da manhã (UTC)
  schedule:
    - cron: "0 6 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: LuanLuizLLs
          filename: assets/metrics.svg

          # Desativa todas as seções padrão
          base: ""

          # Configurações de exibição
          config_display: large
          config_order: languages
          config_timezone: America/Sao_Paulo

          # Estilização do conteúdo
          extras_css: |
            * {
              color: #686D75;
            }

          # Plugin de linguagens
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_colors: 0:#191919, 1:#2c2c2c, 2:#3f3f3f, 3:#545454, 4:#6a6a6a, 5:#808080, 6:#a9a9a9, 7:#d3d3d3
          plugin_languages_limit: 8

          # Plugin de tópicos
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
